name: ci

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build And Push
        uses: appleboy/ssh-action@v0.1.2
        env:
          GB_TOKEN: ${{ secrets.GB_TOKEN }}

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: GB_TOKEN
          script: |
            git clone https://$GB_TOKEN:x-oauth-basic@github.com/overdollc/tali-v2.git
            cd tali-v2
            git checkout master
            git pull origin
            docker-compose up --build --force-recreate -d
